### ISSUE TITLE
Uncaught ReferenceError: DocsAPI is not defined

### ISSUE THREAD

**Issue by bohwaz** [ONLYOFFICE/DocumentServer#1939]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

latest

### Expected Behavior

Document server should be working.

I tried with my own WOPI server and the WOPI server from NextCloud. Same result.

### Actual Behavior

JS console says:

```
Uncaught ReferenceError: DocsAPI is not defined
    at connectEditor (edit?&%3Crs=DC_LLCC&%3E%3Cdchat=DISABLE_CHAT&%3E%3Cembed=EMBEDDED&%3E%3Cfs=FULLSCREEN&%3E%3Chid=HOST_SESSION_ID&%3E%3Crec=RECORDING&%3E%3Csc=SESSION_CONTEXT&%3E%3Cthm=THEME_ID&%3E%3Cui=UI_LLCC&%3E%3Cwopisrc=WOPI_SOURCE&%3E&WOPISrc=http%3A%2F%2Fnextcloud.localhost%2Findex.php%2Fapps%2Fwopi%2Fwopi%2Ffiles%2F23_ocalvg5gbkvs&title=Welcome%20to%20Nextcloud%20Hub.docx&lang=fr-fr&closebutton=1&revisionhistory=1:332:13)
connectEditor @ edit?&%3Crs=DC_LLCC&%3E%3Cdchat=DISABLE_CHAT&%3E%3Cembed=EMBEDDED&%3E%3Cfs=FULLSCREEN&%3E%3Chid=HOST_SESSION_ID&%3E%3Crec=RECORDING&%3E%3Csc=SESSION_CONTEXT&%3E%3Cthm=THEME_ID&%3E%3Cui=UI_LLCC&%3E%3Cwopisrc=WOPI_SOURCE&%3E&WOPISrc=http%3A%2F%2Fnextcloud.localhost%2Findex.php%2Fapps%2Fwopi%2Fwopi%2Ffiles%2F23_ocalvg5gbkvs&title=Welcome%20to%20Nextcloud%20Hub.docx&lang=fr-fr&closebutton=1&revisionhistory=1:332
load (async)
(anonymous) @ edit?&%3Crs=DC_LLCC&%3E%3Cdchat=DISABLE_CHAT&%3E%3Cembed=EMBEDDED&%3E%3Cfs=FULLSCREEN&%3E%3Chid=HOST_SESSION_ID&%3E%3Crec=RECORDING&%3E%3Csc=SESSION_CONTEXT&%3E%3Cthm=THEME_ID&%3E%3Cui=UI_LLCC&%3E%3Cwopisrc=WOPI_SOURCE&%3E&WOPISrc=http%3A%2F%2Fnextcloud.localhost%2Findex.php%2Fapps%2Fwopi%2Fwopi%2Ffiles%2F23_ocalvg5gbkvs&title=Welcome%20to%20Nextcloud%20Hub.docx&lang=fr-fr&closebutton=1&revisionhistory=1:361
```

### Reproduction Steps

1. Install onlyoffice using `docker pull https://hub.docker.com/r/onlyoffice/documentserver/`
2. Install NextCloud + WOPI app, configure WOPI app
3. set up Apache reverse proxy
4. Create docker-compose.yml (attached) and run "docker-compose up"
5. Try to edit a document, blank page + error message

### Additional information

compose.yml:

```
onlyoffice-app:
  image: onlyoffice/documentserver
  container_name: onlyoffice-app
  environment:
    TZ: "Europe/Berlin"
    WOPI_ENABLED: "true"
    USE_UNAUTHORIZED_STORAGE: "true"
    DOCUMENT_SERVER_PORT_80_TCP_ADDR: "nextcloud.localhost"
  expose:
    - 9980
  ports:
    - "9980:80"
  extra_hosts:
    - "nextcloud.localhost:192.168.43.171"
```
