### ISSUE TITLE
NextCloud integration with OnlyOffice crashes 

### ISSUE THREAD

**Issue by masterjg** [ONLYOFFICE/DocumentServer#2382]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.4.1.1

### Expected Behavior

Once the `ONLYOFFICE Docs address` and `Secret key (leave blank to disable)` is input and clicking on `Save` button the integration between NextCloud and OnlyOffice works.

### Actual Behavior

Once I input all the data, set `Authorization header (leave blank to use default header)` to `AuthorizationJwt` and click on `Save` OnlyOffice is bricked (even /healthcheck is not responding). The only way to bring it back is either restart container or `sudo supervisorctl restart ds:docservice`.

Only error in log:
```
root@1046483e417f:/# cat /var/log/onlyoffice/documentserver/nginx.error.log      
2023/09/10 19:50:15 [error] 7111#7111: *9 upstream timed out (110: Unknown error)
 while reading response header from upstream, client: 10.0.4.1, server: , request
: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://127.0.0.1:8000/ConvertS
ervice.ashx", host: "{reverse_proxy_domain}" 
```

### Reproduction Steps

```yml
networks:
    OnlyOffice:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.4.0/24

services:
    MariaDB:
        deploy:
            resources:
                limits:
                    memory: 128M
        environment:
            MYSQL_ROOT_PASSWORD: '{pass}'
            MYSQL_PASSWORD: '{pass}'
            MYSQL_DATABASE: onlyoffice
            MYSQL_USER: onlyoffice
        expose:
            - 3306
        image: mariadb:11.0.3
        networks:
            - OnlyOffice
        restart: unless-stopped
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/tune.cnf:/etc/mysql/conf.d/tune.cnf

    Redis:
        command:
            - redis-server
            - --save
            - 60 1
        deploy:
            resources:
                limits:
                    memory: 32M
        expose:
            - 6379
        image: redis:7.0.12-alpine3.18
        networks:
            - OnlyOffice
        restart: unless-stopped
        sysctls:
            - net.core.somaxconn=65535
        volumes:
            - ./redis/data:/data

    RabbitMQ:
        deploy:
            resources:
                limits:
                    memory: 128M
        environment:
            RABBITMQ_DEFAULT_USER: onlyoffice
            RABBITMQ_DEFAULT_PASS: '{pass}'
        expose:
            - 5672
        image: rabbitmq:3.12.4-alpine
        networks:
            - OnlyOffice
        restart: unless-stopped
        volumes:
            - ./rabbitmq/data:/var/lib/rabbitmq
            - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

    OnlyOffice:
        depends_on:
            - MariaDB
            - Redis
            - RabbitMQ
        deploy:
            resources:
                limits:
                    memory: 512M
        environment:
            DB_TYPE: mariadb
            DB_HOST: mariadb
            DB_PORT: 3306
            DB_NAME: onlyoffice
            DB_USER: onlyoffice
            DB_PWD: '{pass}'
            AMQP_URI: amqp://onlyoffice:{pass}@rabbitmq
            REDIS_SERVER_HOST: redis
            JWT_SECRET: '{pass}'
            JWT_HEADER: AuthorizationJwt
        image: onlyoffice/documentserver:7.4.1.1
        networks:
            - OnlyOffice
        ports:
            - 60004:80
        restart: unless-stopped
        volumes:
            - ./onlyoffice/data:/var/lib/onlyoffice

version: "3.8"
```
![Screenshot from 2023-09-10 23-17-09](https://github.com/ONLYOFFICE/DocumentServer/assets/11464772/8c97a45c-cc72-47cf-938b-4266391a874d)

### Additional information

1. All passwords include special characters, like `!@#$%^&*()_+`.
2. Included example works with no problems
3. Both OnlyOffice and NextCloud are docker containers, running behind reverse proxy
