### ISSUE TITLE
Custom fonts printing problem (Korean languange)

### ISSUE THREAD

**Issue by KhristoforovEvgenii** [ONLYOFFICE/DocumentServer#2668]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.0-ee

### Expected Behavior

1. Сustom fonts should not affect the printing of default fonts
2. Custom fonts should be shown in print window

### Actual Behavior

I have a problem loading certain custom fonts, [here they are ](https://github.com/ONLYOFFICE/DocumentServer/files/14651175/Broken.fonts.zip)

When adding any of these fonts, when printing a document, Korean characters are not displayed even in the standard font as in the screenshot (**Arial**) 
![Product Roadmaps](https://github.com/ONLYOFFICE/DocumentServer/assets/142880987/80dbe699-ef7b-43d5-88fc-7e313f86e863)

I also have a problem with other fonts, they are installed and visible in the editor window, but they also disappear in the print window (but do not cause the same problem as I described above). Here examples of these [fonts](https://github.com/ONLYOFFICE/DocumentServer/files/14653600/fonts_that_are_not_reflect_in_print_mode.zip)
![Product Roadmaps (2)](https://github.com/ONLYOFFICE/DocumentServer/assets/142880987/fdec86ea-8100-4f58-9f2a-c472cf2f06a1)
But some fonts work correctly, for example this 
[work font.zip](https://github.com/ONLYOFFICE/DocumentServer/files/14653709/work.font.zip)

### Reproduction Steps

Issue that breaks default fonts:
1. Put some font from Broken fonts into /usr/share/fonts/custom/ directory in container
2. Type some korean word, e.g. 안녕하세요 (with default font, e.g. Arial)
3. Open print window

Issue that doesn't show custom fonts:
1. Put some font from example fonts archive into /usr/share/fonts/custom/ directory in container 
2. Type some word  (with custom font)
3. Open print window

**Comment by KhristoforovEvgenii** [comment]
@TatianaKirillova hello!
 This is my setup:
1. Running by docker-compose with [onlyoffice/documentserver-ee:7.0](https://hub.docker.com/layers/onlyoffice/documentserver-ee/7.0/images/sha256-e6fb2221f2e0ffeeb64772c54497550c7cfbe5722ff5ceb8a5242ac66594163d?context=explore) image
2. Browser Google Chrome 122.0.6261.128
3. Archive with broken fonts: 
[Broken.fonts.zip](https://github.com/ONLYOFFICE/DocumentServer/files/14719460/Broken.fonts.zip)

**Comment by TatianaKirillova** [comment]
@KhristoforovEvgenii 
Thank you!

**Comment by TatianaKirillova** [comment]
@KhristoforovEvgenii 
In version 8.0.1 the problem does not recur. For reliability of verification, please send the docx file itself, where the text disappears when printed

**Comment by KhristoforovEvgenii** [comment]
@TatianaKirillova here is the file
[example file.docx](https://github.com/ONLYOFFICE/DocumentServer/files/14724614/example.file.docx)
Thank you!

**Comment by KhristoforovEvgenii** [comment]
@TatianaKirillova thank you for the info!
I just tried to deploy document server version 8.0.1 with this configuration:
```
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:8.0.1
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=false
      #- JWT_SECRET=secret
      #- JWT_HEADER=Authorization
      #- JWT_IN_BODY=true
    ports:
      - '88:88'
      - '443:443'
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - /var/www/onlyoffice/Data
       - /var/log/onlyoffice
       - /var/lib/onlyoffice/documentserver/App_Data/cache/files
       - /var/www/onlyoffice/documentserver-example/public/files
       - ./broken_fonts:/usr/share/fonts/truetype/custom

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
```
but the error persisted. (cleared browser cache). 
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/142880987/d82e0387-1ff5-41b1-b4b4-57d426fc0aea)


May be I miss something?
