### ISSUE TITLE
Not working after update DocumentServer 8.2.0 with connector app 9.4.0

### ISSUE THREAD

**Issue by mudza09** [ONLYOFFICE/DocumentServer#2933]
Currently my connector app is version 9.4.0, and I updated OnlyOffice DocumentServer to version 8.2.0 on Ubuntu server 24.04 machine using apt

The installation process went well, but after the update I can't open spreadsheet, doc, pdf, and presentation files

This error message appears:
Cannot GET /8.2.0-88d72bc60b1e714a35888b9a72c76d20/web-apps/apps/spreadsheeteditor/main/index_loader.html

Please help me to fix this problem

**Comment by AzureInformatique** [comment]
> > > The problem is with the cache of your browser. Clear the cache and everything should work fine again.
> > 
> > 
> > Go to hell cache ! Work for me ! Thanks
> 
> which version worked? 8.1.3 or 8.2.0? I am using 8.2.0 and connector app 9.5.0 tried clearing browser cache but still not working

Same as you for the versions, with Chrome and cache clearing it's working

**Comment by mudza09** [comment]
strange, I also use chrome and have cleared the cache but it doesn't work here

**Comment by fvb-sb** [comment]
After reading your comments about a browser cache clearance I gave it another try and updated OnlyOffice Documentserver once again from 8.1.3 to 8.2.0 this morning.
Strangely OnlyOffice Documentserver now works as expected. Even without clearing the browser cache. Tested with Firefox 131.0.3 and Edge 129.0.2792.89.

**Comment by marco-calautti** [comment]
For me, updating to 8.2.0 reintroduces the bug, with and without browser cache clearance. I am using Firefox and Chromium.

Downgrading to 8.1.3 instead fixes the issue only if I also clear the cache.

**Comment by itgi** [comment]
There messed up the path to the index_loader.html. The Version number is not part of the file path but there put it in the code. Remove the Version from the path and it worked. Cannot GET **/8.2.0-88d72bc60b1e714a35888b9a72c76d20**/web-apps/apps/spreadsheeteditor/main/index_loader.html

**Comment by verymilan** [comment]
@itgi interesting... I've tried to just redirect using nginx, but it still complaints:
`Cannot GET /d0566cc58d22570b92963328877b890a/web-apps/apps/documenteditor/main/index_loader.html`

Is it not enough to push the request there?

**Comment by m4tze** [comment]
I am using the docker version of ds-ee V 8.2.0. I have no ds dev experience so I have absolutely no idea of what has changed from 8.1.3 and 8.2.0. The docker version indeed has the same error.

I found out, that the URL ```/8.2.0-88d72bc60b1e714a35888b9a72c76d20/web-apps/apps/spreadsheeteditor/main/index_loader.html``` gives a 404. When removing the first directory (8.2.0-88d72bc60b1e714a35888b9a72c76d20/) I was able to access the html file. Thus, I tried to find the part of code where this directory is added to the string (grep for that string in the apps directory - unfortunately, I cannot do it right now as I am travelling and have no access to the server). I replaced it with just / and after restarting the container, deleting the browser cache and reloading the page, everything works well.

**Comment by marco-calautti** [comment]
I believe [this is the line causing the bug](https://github.com/ONLYOFFICE/web-apps/blob/8b6e1dbf6ff6025632ae3c4750db02949ad458ea/apps/api/documents/api.js#L1214)

In particular, the function extendAppPath is not present in 8.1.3, and in 8.2.0 it prepends the server version and the hash to the URL.

**Comment by m4tze** [comment]
> I believe [this is the line causing the bug](https://github.com/ONLYOFFICE/web-apps/blob/8b6e1dbf6ff6025632ae3c4750db02949ad458ea/apps/api/documents/api.js#L1214)

It was exactly that line . Change it to ```const ver = '/';``` and the problem will disappear.

**Comment by igwyd** [comment]
Hello @mudza09, I guess this happened because you didn't update the nginx config ```ds-docservice.conf```, like this:
![nginx_conf](https://github.com/user-attachments/assets/10d69e3d-81a2-4d59-b3df-e3f899571561)

This file has received an important changes in version 8.2 https://github.com/ONLYOFFICE/document-server-package/commit/18c0e2b6e212b4bf5bec33e6546748f7a3266e5a#diff-30777bc66669cf4e659467a42511b2eef0aabf279ed1f7e26fd8c8bb64be8762 

Agree to overwrite the config file during the update.

**Comment by marco-calautti** [comment]
@igwyd does this also apply to the docker version?

**Comment by igwyd** [comment]
@marco-calautti docker is a delivery with installation inside, if you do not modify it, then there should be no errors. Please tell me how you install and update docker so that I can check.

**Comment by marco-calautti** [comment]
I just leave the tag to "latest" and start my docker compose with
`docker compose up -d`

The image gets updated, the document server starts normally, but I get the bug.

**Comment by marco-calautti** [comment]
The rewrite change seems to be present in the ngix configuration of the 8.2.0 container:
`rewrite ^(?<cache>\/web-apps\/apps\/(?!api\/).*)$ $the_scheme://$the_host$the_prefix/8.2.0-$cache_tag$cache redirect;`

however it does not seem to work. I still the get error.

**Comment by igwyd** [comment]
I checked, but there is no error and I didn't clear the cache. Can you show your docker-compose.yml without private info?

**Comment by marco-calautti** [comment]
This the excerpt of my docker-compose file. I am only reporting how I configure Nextcloud and Onlyoffice:
```yaml
nextcloud:
    container_name: ${NC_CONTAINER_NAME}
    restart: unless-stopped
    image: nextcloud:stable-apache
    cap_add:
      - PERFMON
    devices:
      - "/dev/dri"
    networks:
      - nextcloud-net
    volumes:
      - '${BASE_STORAGE_DIR}/${NC_DATA_DIR}/${NC_CONFIG_DIR}:/var/www/html'
      - type: tmpfs
        target: /tmp
    depends_on:
      nextclouddb:
        condition: service_healthy
      nextcloud-redis:
        condition: service_healthy
      onlyoffice-document-server:
        condition: service_started
    environment:
      - PHP_UPLOAD_LIMIT=500G
      - PHP_MEMORY_LIMIT=4G
      - POST_MAX_SIZE=500G
      - APACHE_BODY_LIMIT=0
      - MYSQL_DATABASE=${NCDB_DATABASE}
      - MYSQL_USER=${NCDB_USER}
      - MYSQL_PASSWORD=${NCDB_PASSWORD}
      - MYSQL_HOST=nextcloud-maria-db
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${NCREDIS_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NC_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NC_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS="${NC_DOMAIN_FREEDNS}"
      - TRUSTED_PROXIES=${NC_SUBNET}
      - OVERWRITECLIURL=https://${NC_DOMAIN_FREEDNS}
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${NC_DOMAIN_FREEDNS}
      - SMTP_HOST=${NC_SMTP_HOST}
      - SMTP_SECURE=${NC_SMTP_SECURE}
      - SMTP_PORT=${NC_SMTP_PORT}
      - SMTP_NAME=${NC_SMTP_USERNAME}
      - SMTP_PASSWORD=${NC_SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=${NC_MAIL_FROM_ADDRESS}
      - MAIL_DOMAIN=${NC_MAIL_DOMAIN}
      - NEXTCLOUD_ENABLE_DRI_DEVICE=true
    labels:
        traefik.enable: true
        traefik.http.routers.nextcloud.entrypoints: websecure

        traefik.http.routers.nextcloud.rule: Host(`${NC_DOMAIN_FREEDNS}`)
        traefik.http.services.nextcloud.loadbalancer.server.port: 80
        traefik.http.routers.nextcloud.tls: true
        traefik.http.routers.nextcloud.tls.certresolver: letsencrypt
        traefik.http.routers.nextcloud.middlewares: nextcloud-dav, nextcloud-sts

        traefik.http.middlewares.nextcloud-dav.redirectregex.permanent: true
        traefik.http.middlewares.nextcloud-dav.redirectregex.regex: "^/.well-known/ca(l|rd)dav"
        traefik.http.middlewares.nextcloud-dav.redirectregex.replacement: "/remote.php/dav/"

        traefik.http.middlewares.nextcloud-sts.headers.stspreload: true
        traefik.http.middlewares.nextcloud-sts.headers.stsseconds: 31536000
        traefik.http.middlewares.nextcloud-sts.headers.isdevelopment: false

        traefik.docker.network: nextcloud-net
        
onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver
    networks:
      - nextcloud-net
      - onlyoffice-net
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      - JWT_ENABLED=true
      - JWT_SECRET=${NC_DOC_SERVER_SECRET}
    depends_on:
      onlyoffice-postgresql:
        condition: service_healthy
      onlyoffice-rabbitmq:
        condition: service_healthy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice.rule=Host(`${NC_DOC_SERVER_DOMAIN_FREEDNS}`)"
      - "traefik.http.routers.onlyoffice.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice.tls.certresolver=letsencrypt"
      - "traefik.http.routers.onlyoffice.tls=true"
      - "traefik.http.routers.onlyoffice.middlewares=onlyoffice-headers"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.onlyoffice-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.onlyoffice-headers.headers.accesscontrolalloworiginlist=*"

      - "traefik.docker.network=onlyoffice-net"
    volumes:
      - ${BASE_STORAGE_DIR}/${NC_DATA_DIR}/${NC_DOC_SERVER_DATA_DIR}/data:/var/www/onlyoffice/Data
      - ${BASE_STORAGE_DIR}/${NC_DATA_DIR}/${NC_DOC_SERVER_DATA_DIR}/log:/var/log/onlyoffice
```
